### ISSUE TITLE
[BUG]: Calling an update for a function does not seem to update the function

### ISSUE THREAD

**Issue by joas8211** [m3o/m3o#142]
### Description

When I try to update a function through M3O Console, the call returns an empty JSON-object. I then call `Describe` to see what the status of the deployment is, but the status is still `Active` and only `updated` property has been changed. When I call the function by requesting it with my browser using the URL I still get the same response as I did with the previous version. So the function has not been updated.

### Additional information

Function description:
```json
{
    "function": {
        "id": "papu",
        "name": "papu",
        "repo": "https://github.com/joas8211/papu-api",
        "branch": "master",
        "entrypoint": "handle",
        "subfolder": "",
        "runtime": "nodejs16",
        "region": "europe-west1",
        "env_vars": {},
        "status": "Active",
        "url": "https://papu.m3o.sh",
        "created": "2022-01-29T21:07:29.873392361Z",
        "updated": "2022-01-30T09:34:16.344030724Z"
    }
}
```

**Comment by asim** [comment]
Thanks for reporting. I know what the issue is. I'll push a fix tomorrow.

**Comment by asim** [comment]
Had a bit of time, bug fix should be out now. Please test and let me know how it goes.

**Comment by joas8211** [comment]
Thanks for the quick reaction. It is working now :tada:
