### ISSUE TITLE
make: *** No rule to make target 'api'. Stop

### ISSUE THREAD

**Issue by lambdaR** [m3o/m3o#145]
### Description

I have noticed a repeated message “**make: *** No rule to make target 'api'. Stop.**” In the log report that corresponds to the “**Generate Go and Js packages**'' step for only two services, **carbon** and **sunnah**, when testing `client-gen` locally, I get only one message for the **sunnah** service.

Is there something special or missing there? old reports and new ones have the same issue
https://github.com/m3o/m3o/runs/5036187631?check_suite_focus=true#step:14:14

**Comment by asim** [comment]
The make files for those services are missing an api function. You can see others in micro/services that have them. Easy to modify and add. I'll do it in a little bit otherwise you can all issue a PR

**Comment by asim** [comment]
Do `ls` in the services folder. The file after carbon is CNAME. The folder after sunnah is test. So the processing is trying to execute makefiles where it shouldn't.
