### ISSUE TITLE
[BUG]: Visual glitch on Sign Up button

### ISSUE THREAD

**Issue by JamesGiesbrecht** [m3o/m3o#15]
### Description

iPad 7 iOS 15.0
Sign Up button is cut in half and overlapping itself.
Refer to screenshot.

### Screenshots

![4B60E0F9-E27F-43A1-81F9-5D60A5740128](https://user-images.githubusercontent.com/40125881/138161989-7b7a7726-33a0-4a31-9ae9-167e940714fa.png)

**Comment by cyb3rko** [comment]
Seems to be fixed.
Can you confirm that?

**Comment by JamesGiesbrecht** [comment]
Can confirm, issue is resolved.
