### ISSUE TITLE
[BUG]: ResetPassword 

### ISSUE THREAD

**Issue by BataBoom** [m3o/m3o#154]
### Description

Sending Code/newPassword to ResetPassword endpoint results in Go Error 

Sample Request:
$curl->setBasicAuthentication('Authorization', $userAPItoken);
$curl->setHeader('Content-Type', 'application/json');
$curl->post('https://api.m3o.com/v1/user/ResetPassword', [
'code' => $code,
'confirmPassword' => $pass,
'email' => $email,
'newPassword' => $pass

Result: 

object(stdClass)#8 (4) { ["Id"]=> string(15) "go.micro.client" ["Code"]=> int(500) ["Detail"]=> string(76) "json: cannot unmarshal string into Go value of type domain.passwordResetCode" ["Status"]=> string(21) "Internal Server Error" }

**Comment by domwong** [comment]
Hi, we've just deployed a fix for this. Should be all good now
