### ISSUE TITLE
[BUG]: Space API returning 500

### ISSUE THREAD

**Issue by mawoka-myblock** [m3o/m3o#159]
### Description

If I upload a file to the `https://api.m3o.com/v1/space/Create`-Endpoint and try to get it from the `https://api.m3o.com/v1/space/Read`, it works. After some time (different each time), I get the following error when trying to retrieve the file:
```json
{"Id":"space.Read","Code":500,"Detail":"Error reading object","Status":"Internal Server Error"}
```
The file is still listed, if I use the `List`-Endpoint, but I get this 500.

### Additional information

It is very inconsistent when the issue occurs. Sometimes after 2 retrieves with a 2 second break after it, sometimes after the 10th retrieve and a 30 seconds break.
I uploaded the file via the JavaScript SDK and the filename is just a cuid  without a file-ending (cuid slightly modified uuid)

**Comment by domwong** [comment]
Thanks for raising this. Fix has been deployed so should be OK now.
