### ISSUE TITLE
[BUG] Internal server error (Response 500) while creating function.

### ISSUE THREAD

**Issue by ErrorxCode** [m3o/m3o#196]
### Description

I was deploying a java function onto the cloud from the [UI](https://cloud.m3o.com/functions/add) but It didn't succeed, Nor did it show any error. My project structure is exactly like as google described in their [docs](https://cloud.google.com/functions/docs/create-deploy-http-java#gradle). When I opened the console, I saw an error response there.
It was as follows :-
```json
{id: 'function.deploy', code: 500, detail: 'zip: not a valid zip file', status: 'Internal Server Error'}
```
The worst thing is that UI does not describe that error.

My java function: https://github.com/ErrorxCode/FuncDemo

### Screenshots

![image](https://user-images.githubusercontent.com/65817230/157201001-afd73de0-eff0-4107-a185-1364528e6a89.png)

### Additional information

This BUG 🐛 is not evaluated on the front-end and hence the UI buttons do nothing on "Submitting" the function.

**Comment by asim** [comment]
The repo does not exist. Where is the code and what are you naming the function?
