### ISSUE TITLE
[Image API] Adjustable compression rate/lossless upload

### ISSUE THREAD

**Issue by habovh** [m3o/m3o#25]
### Description

I think this would make a lot of sense to optimise bandwidth & storage space.

A very practical case: I've got some images that are already optimised for my specific app. If I upload them using the Image API, [they end up being encoded again by Go's `png.Encode` or `jpeg.Encode` using default parameters](https://github.com/micro/services/blob/c70dabf4a0c4a62aa86127f1bf7e4335e01fa529/image/handler/image.go#L86-L89).

In my specific case, it would be nice to be able to upload the image without any processing. Maybe just a type check to ensure only images are uploaded?

However, for most cases it would be enough to be able to provide the "quality" parameter. An arbitrary value between 0 and 1, 1 being the highest quality possible.

**Comment by domwong** [comment]
@habovh we've done a bit of a refactor of the api so it now does a direct upload rather than re-encoding. Have also added the ability to do a direct file upload using `multipart/form-data` rather than having to base64 encode the image

https://github.com/micro/services/blob/master/image/handler/image.go#L48-L89

**Comment by habovh** [comment]
@domwong sounds like a good solution! The addition of `multipart/form-data` is quite nice as well. I'm just a bit concerned about security here: it seems —to my untrained JS developer eye— that there's no check on the file itself before upload. The previous implementation had the benefit to ensure only pictures are uploaded. It's not likely to cause issues from a developer or user point of view as it's more an issue of input sanitisation on your side, but I thought it was worth mentioning.

**Comment by domwong** [comment]
That's a good point, have addressed it in this PR https://github.com/micro/services/pull/267
