### ISSUE TITLE
api=image upload function improvement

### ISSUE THREAD

**Issue by rowntreerob** [m3o/m3o#6]
current use of base64 strings is out-of-date in big way. Update this to use node streams and to use streams with pipes where possible. sample code similar to how update might work 

https://reqbin.com/req/c-dot4w5a2/curl-post-file#:~:text=To%20post%20a%20file%20with,the%20%2DF%20option%20several%20times.

https://jsfiddle.net/rowntreerob/c94f5t3k/99/

**Comment by domwong** [comment]
@rowntreerob we've updated the api so you should be able to upload files directly. 

e.g. 

```
curl https://api.m3o.com/v1/image/upload -H "Authorization: Bearer XXX" -F name=cup.jpg -F file=@cup.jpg 

{"url":"https://cdn.m3ocontent.com/micro/images/micro/a0e73f1e-f71e-4cd0-af1f-375242cf11c1/cup.jpg"}
```
