### ISSUE TITLE
[BUG] [DB]: orderBy of read endpoint orders attribute values as strings even when attribute values are numbers

### ISSUE THREAD

**Issue by osofem** [m3o/m3o#60]
### Description

```
{
    "limit": 0,
    "order": "desc",
    "orderBy": "someAttribute",
    "table": "someTableName"
}
```

The `orderBy` of the `read` endpoint for `DB` orders values as string even when they are clearly numbers. The implication is that string `"9"` is greater than string `"16"`.

**Comment by crufter** [comment]
I can confirm this is the case, will be fixed shortly.

**Comment by crufter** [comment]
Fix is in live now.
