### ISSUE TITLE
[Feature Request] Image URL to Base64

### ISSUE THREAD

**Issue by DATL4G** [m3o/m3o#61]
Please extend the current Image API to convert a image url to Base64.

This is useful for example when the image url is blocked in the users DNS, so we can get a Base64 string from it and decode it on the client.

**Comment by crufter** [comment]
Nice idea. Put on the todo list.

**Comment by crufter** [comment]
This should be fixed, try

```
'{"url": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"}'
```
