### ISSUE TITLE
[BUG]: DB get slower as size increases

### ISSUE THREAD

**Issue by osofem** [m3o/m3o#67]
### Description

I noticed the retrieval of records from DB gets slower as table size grow.

**Comment by crufter** [comment]
What is your current DB size (record count)? How big is the result set (in kilobytes)?

**Comment by asim** [comment]
Can you please provide more info, which tables, what data exists in those tables. How slow. Where are you querying it from. Is it the same in the Ui?

**Comment by osofem** [comment]
@crufter count is 487 records and when I copied the entire table content and save in a txt file, it's 570kb. A single record is around 9kb but this will vary of course.

**Comment by asim** [comment]
Are you reading all the records in one call or record by record?

**Comment by asim** [comment]
Can you also provide the response time exactly from your call

**Comment by crufter** [comment]
I have a table with 5k records and a simple list returns in 377ms.
Same speed for a query that filters it down to 1 record.

**Comment by osofem** [comment]
@crufter With this, I want to believe the lag could be from my end. I will isolate the exact function that does the retrieval and revert on my findings

**Comment by osofem** [comment]
I can confirm this is not from M3O's ends. Retrieval is taking just 1.6sec from my production server when I isolated the retrieval function (though execution time is exceeding 5 secs).

Apologies to have bothered the team.

![image](https://user-images.githubusercontent.com/5585183/141111181-c1f792df-44f9-4b01-872f-540eeb19ae6c.png)
