### ISSUE TITLE
[User] Force set password

### ISSUE THREAD

**Issue by SamDev-7** [m3o/m3o#70]
### Description

Set an account's password without requiring the old password. 
Should be kept separate from the current `Update Password` endpoint.

Useful if a user forgets their password.

**Comment by asim** [comment]
Should the reset functionality accept a new password, return one or send an email?

**Comment by SamDev-7** [comment]
Here's what I'm imagining.

## `ResetPassword` endpoint.
`userId` the account id
`newPassword` the new password
`confirmPassword` confirm new password

## `SendPasswordResetEmail` endpoint.
*Similar as Send Verification Email*
*Email has to be verified?*

**Comment by asim** [comment]
You should now see these 2 endpoints https://m3o.com/user
