### ISSUE TITLE
[BUG]: Intermittent 408 timeouts calling db

### ISSUE THREAD

**Issue by alexander-daniel** [m3o/m3o#74]
### Description

I have an API endpoint that receives an email, and we store it in the database.

This is the code:

```js
  const { DbService } = require("m3o/db");
  const dbService = new DbService(process.env.M3O_API_TOKEN)

// Wrapped in an http handler
  await dbService.create({
    record: {
      id: email,
      subscriptionId, 
      verified: false,
    },
    table: process.env.SUBSCRIBERS_DB_TABLE_NAME,
  });

```

Most of the time it works fine, sometimes I get the 408:
```js
{
  Id: 'go.micro.client',
  Code: 408,
  Detail: 'context deadline exceeded',
  Status: 'Request Timeout'
}
```

Happens locally and remotely. Thank you for your time!

**Comment by domwong** [comment]
Thanks for the report. I'm looking at this now

**Comment by domwong** [comment]
I think this is a symptom of occasional more general slow downs on the DB. I've made some tweaks to squash some of the more obvious occurrences but if you keep seeing this please reply on this thread with approx time of the `408`s.

**Comment by alexander-daniel** [comment]
Thank you for taking a look. It happened again at ~ 19h19 - 19h20 EST.

**Comment by alexander-daniel** [comment]
Tried again this AM, had another case at 10h48 AM EST, 10th of November 2021. To be clear, I am making only two DB write calls. I am not spamming or anything, this is just a simple db write....

**Comment by domwong** [comment]
Can I just double check - I can see a successful call to db.Create at 10h48 EST (should have returned a `200`). But I also see a timeout call to email.Send at 10h48 too. I don't have enough information to correlate to a particular user - is it possible that was your call?

**Comment by alexander-daniel** [comment]
Possibly. I `truncate`d my db before testing again.

**Comment by domwong** [comment]
OK thanks. Still doing some tweaks across the whole platform to reduce the incidence of timeouts. Have done a few more changes to loosen up timeouts which should help some more but please feel free to keep this issue open until you're satisfied that it's not a regular occurence
