### ISSUE TITLE
weather.Forecast go example returns incorrect result

### ISSUE THREAD

**Issue by lambdaR** [m3o/m3o#77]
### Description

```
package main
  
import (
        "fmt"

        "go.m3o.com/weather"
)

// Get the weather forecast for the next 1-10 days

func main() {

        weatherService := weather.NewWeatherService(<TOKEN>)

        rsp, err := weatherService.Forecast(&weather.ForecastRequest{

                Days: 2,

                Location: "london",
        })

        fmt.Println(rsp, err)

}
```

returns this 

`&{ [{0 0 0 Partly cloudy 2021-11-18  0 0 0 0 07:24 AM 04:07 PM false} {0 0 0 Partly cloudy 2021-11-19  0 0 0 0 07:26 AM 04:06 PM false}] 0   0  } <nil>`

weather.Now has a similar issue too.

**Comment by asim** [comment]
All the values being returned as zero are floats. This works in the UI but the Go client appears to be having some issues with conversion maybe. I believe there was some sort of code change a couple weeks back. Even curl works so I know the api is not the issue. Will have a look a bit later tonight.

**Comment by asim** [comment]
OK so I can see what's happening.

JSON response is
```
{
    "forecast": [
        {
            "date": "2021-11-18",
            "max_temp_c": 13.3,
            "max_temp_f": 55.9,
            "min_temp_c": 7.1,
            "min_temp_f": 44.8,
            "avg_temp_c": 10,
            "avg_temp_f": 50,
            "condition": "Partly cloudy",
            "icon_url": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "sunrise": "07:24 AM",
            "sunset": "04:07 PM"
        },
        {
            "date": "2021-11-19",
            "max_temp_c": 14.2,
            "max_temp_f": 57.6,
            "min_temp_c": 8.8,
            "min_temp_f": 47.8,
            "avg_temp_c": 10.9,
            "avg_temp_f": 51.6,
            "condition": "Partly cloudy",
            "icon_url": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "sunrise": "07:26 AM",
            "sunset": "04:06 PM"
        }
    ]
}
```

Whereas the struct has tags that are snake case

```
type Forecast struct {
        // the average temp in celsius
        AvgTempC float64 `json:"avgTempC"`
        // the average temp in fahrenheit
        AvgTempF float64 `json:"avgTempF"`
        // chance of rain (percentage)
        ChanceOfRain int32 `json:"chanceOfRain"`
        // forecast condition
        Condition string `json:"condition"`
        // date of the forecast
        Date string `json:"date"`
        // the URL of forecast condition icon. Simply prefix with either http or https to use it
        IconUrl string `json:"iconUrl"`
        // max temp in celsius
        MaxTempC float64 `json:"maxTempC"`
        // max temp in fahrenheit
        MaxTempF float64 `json:"maxTempF"`
        // minimum temp in celsius
        MinTempC float64 `json:"minTempC"`
        // minimum temp in fahrenheit
        MinTempF float64 `json:"minTempF"`
        // time of sunrise
        Sunrise string `json:"sunrise"`
        // time of sunset
        Sunset string `json:"sunset"`
        // will it rain
        WillItRain bool `json:"willItRain"`
}
```

I don't know if this changed or whether its always been broken. I will look to fix.

**Comment by asim** [comment]
So the issue we have is the way the client is generated. It uses the openapi spec which has camelcase field names, despite the response being underscores. We have a number of places where it somewhat differs. So we need to look into where to fix. Ideally it would be good to ensure everything on the backend is uniform first. But also have the clients handle differences.

**Comment by asim** [comment]
https://github.com/m3o/m3o/pull/78/files

I have this fix. The issue now is, it will cause the JS clients to have snake case fields because I'm not entirely sure how you map those correctly. Might need a hand with that before merging this.

**Comment by lambdaR** [comment]
I discovered this issue by accident. Actually, I am not using the go weather client at the moment. I only tried to write a dart weather client using the go weather client as a guide. so , when I run the dart client it returns a result with a snake-case but the go code that I am using as a guide has a camel case which confused me a lot.

Since M3O is still in beta, I do agree with you about the necessity to ensure that everything coming from the M3O backend is uniform by checking whether 3rd party API comply with the openapi standard or not and implement the conversion (whatever format they use -> camel case) at the service level if needed.

**Comment by asim** [comment]
```
	// the average temp in celsius
	AvgTempC float64 `protobuf:"fixed64,6,opt,name=avg_temp_c,json=avgTempC,proto3" json:"avg_temp_c,omitempty"`
	// the average temp in fahrenheit
	AvgTempF float64 `protobuf:"fixed64,7,opt,name=avg_temp_f,json=avgTempF,proto3" json:"avg_temp_f,omitempty"`
	// will it rain
	WillItRain bool `protobuf:"varint,8,opt,name=will_it_rain,json=willItRain,proto3" json:"will_it_rain,omitempty"`
```

Here's an example of what protoc-gen-go generates. You can see the field tags, protobuf and json. Where protobuf also includes its own json tag which is camelcase despite the actual json tag being snake case. The openapi generator looks at this and uses the json tag thats defined by protobuf. This is largely for jsonpb. But for some reason in our case we're not receiving that kind of response. 

I can either try to fix the output response from the service so its always using the protobuf defined json value, or mess with the openapi generator and generated code basically. Having created this PR, I think my next step is to dig into why I'm not receiving the protobuf defined json keys.

**Comment by lambdaR** [comment]
have you tried protojson before? it seems that this package deals with that kind of problem https://pkg.go.dev/google.golang.org/protobuf@v1.27.1/encoding/protojson here is also an article that you might find it useful dealing with a similar problem https://seb-nyberg.medium.com/customizing-protobuf-json-serialization-in-golang-6c58b5890356

**Comment by asim** [comment]
This should now be fixed in the latest version. Please confirm and close if all good.

**Comment by lambdaR** [comment]
confirmed ... closing
