### ISSUE TITLE
return an error message when using stream(websocket) with invalid token

### ISSUE THREAD

**Issue by lambdaR** [m3o/m3o#80]
### Description

Currently, when you run helloworld **stream** for example, with invalid token the connection just hangs with no indication of what happened.
It would be better if the backend returns a message  like `{id: v1, code: 401, detail: Unauthorized, status: Unauthorized}` instead.

**Comment by domwong** [comment]
Thanks for the report. Will take a look

**Comment by domwong** [comment]
@lambdaR just deployed a fix for you, thanks for the useful feedback as always
